theta = 0:0.02:10;
x=theta; 
rho=sin(2*theta).*cos(2*theta);
figure(1);
title('polar curves');
style=polar(theta,rho,'--g');
style.LineWidth = 3;
y=10*x.*x;
figure(2);
subplot(2,2,1);
plot(x,y,'LineWidth',3);
title('plot(x,y)');
grid on;
subplot(2,2,2);
semilogx(x,y,'LineWidth',3);
title('semilogx(x,y)');
grid on;
subplot(2,2,3);
semilogy(x,y,'LineWidth',3);
title('semilogy(x,y)');
grid on;
subplot(2,2,4);
loglog(x,y,'LineWidth',3);
title('loglog(x,y)');
grid on;